## These functions allow for caching the inverse of a given matrix so that the inverse can be retrieved later
## without the need to recalculate

## Creates "matrix" object that is a list of functions for storing/modifying a given matrix's inverse

makeCacheMatrix <- function(x = matrix()) {
        ##initialize inverse to NULL as it has not been calculated yet
    inv <- NULL
    
        ##create set/get functions for the given matrix and its inverse and generate a list that serves as the cache
    set <- function(y) {
        x <<- y
        inv <<- NULL
    }
    get <- function() x
    setInv <- function(inverse) inv <<- inverse
    getInv <- function() inv
    list (set = set, get = get, setInv = setInv, getInv = getInv)
}


## Given a "matrix" object generated by makeCacheMatrix, this function obtains the cached inverse or calculates the inverse
## using solve() and caches it in the "matrix" object for future use

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
    
        ## return cached value if it exists, i.e., inv is not null
    inv <- x$getInv()
    if(!is.null(inv)) {
        message("getting cached data")
        return(inv)
    }
    
        ## otherwise, calculate the inverse now and cache it
    data <- x$get()
    inv <- solve(data, ...)
    x$setInv(inv)
    inv
}

